name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Test workflow
      uses: snakemake/snakemake-github-action@master
      with:
        directory: .test
        snakefile: Snakefile
        args: "--use-conda --show-failed-logs"
